### PR TITLE
No longer writing empty sets

### LINKED ISSUE #113: We must not write of empty sets to DDB - instead do a NOP
In the AWS interpreter we must not write of empty sets - instead do a NOP - otherwise DDB will return an error `software.amazon.awssdk.services.dynamodb.model.DynamoDbException: One or more parameter values were invalid: An string set  may not be empty`.

This is a limitation of DDB see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.Document

> An attribute value cannot be an empty set (string set, number set, or binary set), however, empty lists and maps are allowed

### PR DESCRIPTION
**Pull request by nhyne**
Not writing empty sets anymore. Also added a test to the integration tests so we don't run into this again.

Closes #113

### CODE REVIEW

File: dynamodb/src/main/scala/zio/dynamodb/AttrMap.scala [hunk 1]
```diff
@@ -1,5 +1,9 @@
 package zio.dynamodb
 
+import io.github.vigoo.zioaws.dynamodb.model.primitives.AttributeName
+import zio.dynamodb.DynamoDBExecutorImpl.awsAttributeValue
+import io.github.vigoo.zioaws.dynamodb.model.{ AttributeValue => ZIOAWSAttributeValue }
```
Comment (googley42) [inline dynamodb/src/main/scala/zio/dynamodb/AttrMap.scala:5]: `AttrMap` is a pure model ATM and this change will make it depend directly on `zio-aws` . I think we need to keep the separation of concerns between the model and the underlying DB client library as much as possible so that in future we could do things like swap out the DB lib more easily (eg for say a pure Scala lib if one becomes available) . Also the `AttrMap` model and machinery could potentially be extracted to its own module or lib in the future.

How about for now creating a function or an implicit extension method for AttrMap in DynamoDBExecutorImpl.scala where `toZioAwsMap` is used that takes an AttrMap and returns a `Map[AttributeName, ZIOAWSAttributeValue]` eg
```scala
  implicit class ToZioAwsMap(item: AttrMap) {
    def toZioAwsMap(): Map[AttributeName, ZIOAwsAttributeValue] =
      item.map.flatMap { case (k, v) => awsAttributeValue(v).map(a => (k, a)) }
  }
```
?

**Review by googley42 — COMMENTED** [review]
Looks good, just one comment about the model

File: dynamodb/src/main/scala/zio/dynamodb/AttrMap.scala (hunk 1 above)
Comment (nhyne) [reply dynamodb/src/main/scala/zio/dynamodb/AttrMap.scala:5]: This sounds a lot better to me, I'll make some changes tonight to clean it up.

**Review by googley42 — APPROVED** [review]

**Comment by googley42** [comment]
Ah - one think I forgot to mention is that all these fixes also need to be applied to the ZIO 2.0 branch as well
